apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
type: Opaque
stringData:
  ConnectionStrings__Connection: "Server=192.168.0.78,1433;Database=EsperancaSolidariaCampaign;User Id=hackathon;Password=Hackathon@123;TrustServerCertificate=true"